import random
import TC
from RandomisationandPythonLists import Final_Prj
import game_1 
import game_2




#? NEED TO CREATE A VARIABLE THAT HOLD BOTH WINNERS FROM GAME_1 AND GAME_2 TO REACH THE FINAL DRAW

#? TRY TO DIVISION TO MULTIPLE FUNDCTION AND PLAY WITH VARIBALES 